var CRMClient_1 = require("./CRM/CRMClient");
var Guid_1 = require("./CRM/Guid");
var crm = new CRMClient_1.CRMClient("default");
console.log(process.env["EDGE_CS_DEBUG"]);
process.env["EDGE_CS_DEBUG"] = 1;
var who = crm.WhoAmI();
console.log(who);
var myUser = crm.retrieve("systemuser", new Guid_1.Guid(who), true);
console.log(myUser);
var account1 = crm.retrieve("account", new Guid_1.Guid("4C1ECDF4-633B-E211-9EB5-0050568A69E2"), ["accountid", "name", "ownerid", "createdon"]);
console.log(account1);
var account2 = crm.retrieve("account", new Guid_1.Guid("4C1ECDF4-633B-E211-9EB5-0050568A69E2"), true);
console.log(account2);
